<?php
$height += 206;
$ticker = "AVAX";
$coin = "Avalanche";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;">Website:</th><td style="text-align:left;"><a href="https://www.avalabs.org">www.avalabs.org</a></td></tr>
<tr><th style="text-align:left;">Contract:</th><td style="text-align:left;">0x1ce0c2827e2ef14d5c4f29a091d735a204794041 (BSC)</td></tr>
</table>
</div>
