<?php
$height += 206;
$ticker = "BAT";
$coin = "Basic Attention Token";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;" rowspan="2" valign="top">Contract:</th><td>0x101d82428437127bf1608f699cd651e6abf9766e (BSC)</td></tr>
<tr><td style="text-align:left;">0x0d8775f648430679a709e98d2b0cb6250d2887ef (Ethereum)</td></tr>
</table>
</div>
