<?php
$height += 206;
$ticker = "COVAL";
$coin = "Circuits of Value";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;">Website:</th><td style="text-align:left;"><a href="https://circuitsofvalue.com">circuitsofvalue.com</a></td></tr>
<tr><th style="text-align:left;" rowspan="2" valign="top">Contract:</th><td>0xd15cee1deafbad6c0b3fd7489677cc102b141464 (BSC)</td></tr>
<tr><td style="text-align:left;">0x3d658390460295fb963f54dc0899cfb1c30776df (Ethereum)</td></tr>
</table>
</div>
