<?php
$height += 206;
$ticker = "DOT";
$coin = "Polkadot";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;">Website:</th><td style="text-align:left;"><a href="https://polkadot.network">polkadot.network</a></td></tr>
<tr><th style="text-align:left;">Contract:</th><td style="text-align:left;">0x7083609fce4d1d8dc0c979aab8c869ea2c873402 (BSC)</td></tr>
</table>
</div>
