<?php
$height += 206;
$ticker = "MKR";
$coin = "Maker token";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;" rowspan="2" valign="top">Contract:</th><td>0x5f0da599bb2cccfcf6fdfd7d81743b6020864350 (BSC)</td></tr>
<tr><td style="text-align:left;">0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2 (Ethereum)</td></tr>
</table>
</div>
