<?php
$height += 206;
$ticker = "PATS";
$coin = "PatexShares";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;" rowspan="2" valign="top">Contract:</th><td>0xf256dab35000b260252015891f06179ea41bcad5 (BSC)</td></tr>
<tr><td style="text-align:left;">0x3310f5acb5df71da3b15a27230122bfbf3f7b9a0 (Ethereum)</td></tr>
</table>
</div>
