<?php
$height += 206;
$ticker = "SLP";
$coin = "Smooth Love Potion";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;">Website:</th><td style="text-align:left;"><a href="https://axieinfinity.com">axieinfinity.com</a></td></tr>
<tr><th style="text-align:left;">Contract:</th><td style="text-align:left;">0xcc8fa225d80b9c7d42f96e9570156c65d6caaa25 (Ethereum)</td></tr>
</table>
</div>
