<?php
$height += 206;
$ticker = "USDP";
$coin = "Pax Dollar";
$image = "https://cryptoradar.exchange/img/icon-".strtolower($ticker).".png";
?>
<div style="height:200px;margin-top:6px;">
<span id="icon">
<?php
echo '<img src="'.$image.'" width=32>';
?>
</span><span style="font-size:32px;">&nbsp;
<?php
echo $coin; 
?>
</span>
<br />
<table>
<tr><th style="text-align:left;">Website:</th><td style="text-align:left;"><a href="https://paxos.com/usdp/">paxos.com/usdp/</a></td></tr>
<tr><th style="text-align:left;" rowspan="2" valign="top">Contract:</th><td>0xb3c11196a4f3b1da7c23d9fb0a3dde9c6340934f (BSC)</td></tr>
<tr><td style="text-align:left;">0x8e870d67f660d95d5be530380d0ec0bd388289e1 (Ethereum)</td></tr>
</table>
</div>
